/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mailcoverorganizer;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.util.Properties;
import javax.swing.ImageIcon;

//Reference for the print function: https://www.youtube.com/watch?v=ivSPqBGT4EQ

import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.text.Document;

/**
 *
 * @author spitz
 */
public class FinalCoverJFrame extends javax.swing.JFrame {

    /**
     * Creates new form FinalCoverJFrame
     */
    
    String title;
    String date;
    String category;
    ImageIcon image;
    String location;
    String description;
    int imageX, imageY;
    int destX = 275;
    int destY = 175;
    int fullWidth = 400;
    
    public FinalCoverJFrame(String t, String da, String c, ImageIcon i, String l, String de) {
        initComponents();
        title = t;
        date = da;
        category = c;
        image = i;
        location = l;
        description = de;
        
        //proportion calculation
        imageX = image.getIconWidth();
        imageY = image.getIconHeight();

        if(imageY > imageX){
            destX = (destY*imageX)/imageY;
        }
        else
        {
            destY = (destX*imageY)/imageX;
        }
        imageLabel.setLocation(((fullWidth-imageLabel.getWidth())/2), 200);
        
        if (image.getIconWidth() > image.getIconHeight())
        {
            
            imageLabel.setLocation(imageLabel.getX(), imageLabel.getY() + 150);
            imageLabel.repaint();
            imageLabel.revalidate();
        }
        begin();
    }
    
        private void begin(){
        titleLabel.setText(title);
        dateLabel.setText(date);
        ImageIcon imageIcon = new ImageIcon(image.getImage().getScaledInstance(destX, destY, Image.SCALE_AREA_AVERAGING));
        imageLabel.setIcon(imageIcon);
        imageLabel.setText("");
        locationLabel.setText(location);
        eventLabel.setText(category);
        descriptionText.setText(description);
        descriptionText.setWrapStyleWord(true);
        
        titleLabel.setLocation(((fullWidth-titleLabel.getWidth())/2), 100);
        
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fullScreen = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        locationLabel = new javax.swing.JLabel();
        eventLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        descriptionScroll = new javax.swing.JScrollPane();
        descriptionText = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(400, 517));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 517));

        fullScreen.setBackground(new java.awt.Color(255, 255, 255));
        fullScreen.setForeground(new java.awt.Color(255, 255, 255));
        fullScreen.setMaximumSize(new java.awt.Dimension(400, 517));
        fullScreen.setMinimumSize(new java.awt.Dimension(400, 517));
        fullScreen.setPreferredSize(new java.awt.Dimension(400, 517));

        imageLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setText("Image here...");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 100));

        locationLabel.setBackground(new java.awt.Color(0, 0, 0));
        locationLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        locationLabel.setText("Location");

        eventLabel.setBackground(new java.awt.Color(0, 0, 0));
        eventLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        eventLabel.setText("Event");

        titleLabel.setBackground(new java.awt.Color(0, 0, 0));
        titleLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Event Title");
        titleLabel.setMaximumSize(new java.awt.Dimension(375, 30));
        titleLabel.setMinimumSize(new java.awt.Dimension(5, 5));

        dateLabel.setBackground(new java.awt.Color(0, 0, 0));
        dateLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLabel.setText("Date");
        dateLabel.setMaximumSize(new java.awt.Dimension(375, 24));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(locationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                .addComponent(eventLabel)
                .addGap(30, 30, 30))
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eventLabel)
                    .addComponent(locationLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        descriptionScroll.setBorder(null);
        descriptionScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        descriptionScroll.setPreferredSize(new java.awt.Dimension(300, 120));

        descriptionText.setEditable(false);
        descriptionText.setColumns(20);
        descriptionText.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        descriptionText.setLineWrap(true);
        descriptionText.setRows(5);
        descriptionText.setBorder(null);
        descriptionText.setPreferredSize(new java.awt.Dimension(300, 120));
        descriptionScroll.setViewportView(descriptionText);

        saveButton.setText("Save as PDF");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fullScreenLayout = new javax.swing.GroupLayout(fullScreen);
        fullScreen.setLayout(fullScreenLayout);
        fullScreenLayout.setHorizontalGroup(
            fullScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fullScreenLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(fullScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fullScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fullScreenLayout.createSequentialGroup()
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeButton))
                    .addGroup(fullScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(descriptionScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fullScreenLayout.setVerticalGroup(
            fullScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fullScreenLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(descriptionScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fullScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(closeButton))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fullScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fullScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        saveButton.setVisible(false);
        closeButton.setVisible(false);
        exportPDF(fullScreen);
        saveButton.setVisible(true);
        closeButton.setVisible(true);
    }//GEN-LAST:event_saveButtonActionPerformed

    
    private void exportPDF(JPanel panel){
        
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        
        printerJob.setJobName("Printed Panel");
        
        printerJob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if (pageIndex > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D graphics2D = (Graphics2D)graphics;
                
                graphics2D.translate(0, pageFormat.getImageableY()*2);
                
                
                graphics2D.scale(1.55, 1.55);
                
                
                panel.paint(graphics2D);
                
                return Printable.PAGE_EXISTS;
            }
        });
        
        boolean returningResult = printerJob.printDialog();
        
        if(returningResult){
            
            try{
                
                printerJob.print();
                
            } 
            
            catch (PrinterException printerException){
                JOptionPane.showMessageDialog(this, "Print Error: " + printerException.getMessage());
            }
            
        }
 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JScrollPane descriptionScroll;
    private javax.swing.JTextArea descriptionText;
    private javax.swing.JLabel eventLabel;
    private javax.swing.JPanel fullScreen;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
