/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mailcoverorganizer;

import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author spitz
 */
public class MenuJFrame extends javax.swing.JFrame {

public MailCoverOrganizer mco;
    
    /**
     * Creates new form MenuJFrame
     */
    public MenuJFrame(MailCoverOrganizer mco) {
        this.mco = mco;
        initComponents();
        begin();
    }
    
    public void begin(){
        feedbackLabel.setForeground(Color.BLACK);
        feedbackLabel.setText("");
        saveButton.setEnabled(false);  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        menuAddCoverButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuSearchForCoverButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        feedbackLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(720, 480));

        menuAddCoverButton.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        menuAddCoverButton.setText("Add Cover");
        menuAddCoverButton.setMaximumSize(new java.awt.Dimension(80, 35));
        menuAddCoverButton.setMinimumSize(new java.awt.Dimension(80, 35));
        menuAddCoverButton.setPreferredSize(new java.awt.Dimension(80, 35));
        menuAddCoverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddCoverButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mail Cover Organizer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        menuSearchForCoverButton.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        menuSearchForCoverButton.setText("Search for Cover");
        menuSearchForCoverButton.setMinimumSize(new java.awt.Dimension(171, 35));
        menuSearchForCoverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSearchForCoverButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Load");
        loadButton.setMaximumSize(new java.awt.Dimension(110, 50));
        loadButton.setMinimumSize(new java.awt.Dimension(110, 50));
        loadButton.setPreferredSize(new java.awt.Dimension(110, 50));
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.setMaximumSize(new java.awt.Dimension(110, 50));
        saveButton.setMinimumSize(new java.awt.Dimension(110, 50));
        saveButton.setPreferredSize(new java.awt.Dimension(110, 50));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        feedbackLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        feedbackLabel.setText("Default Text");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(menuSearchForCoverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuAddCoverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(feedbackLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(229, 229, 229))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(menuAddCoverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuSearchForCoverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(feedbackLabel)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAddCoverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddCoverButtonActionPerformed
        // TODO add your handling code here:
        refresh();
        mco.addCoverJFrame.resetValues();
        mco.switchScreen(MailCoverOrganizer.screen.ADD);
    }//GEN-LAST:event_menuAddCoverButtonActionPerformed

    private void menuSearchForCoverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSearchForCoverButtonActionPerformed
        // TODO add your handling code here:
        refresh();
        mco.switchScreen(MailCoverOrganizer.screen.SEARCH);
    }//GEN-LAST:event_menuSearchForCoverButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // TODO add your handling code here:
        mco.allCovers.clear();
        mco.searchResultsJFrame.previewPanels.clear();
        mco.searchResultsJFrame.clearAllOnPage();
        mco.readJSON();
        if (mco.allCovers.size() > 0){
            feedbackLabel.setForeground(Color.GREEN);
            feedbackLabel.setText("Load Successful");
        } 
        else
        {
            feedbackLabel.setForeground(Color.RED);
            feedbackLabel.setText("Load Unsuccessful"); 
        }
        refresh();
    }
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        mco.writeJson();
    }                                          
    
    public void saveComplete(){
        feedbackLabel.setForeground(Color.GREEN);
        feedbackLabel.setText("Successfully Saved");
    }
    
    public void saveIncomplete(){
        feedbackLabel.setForeground(Color.RED);
        feedbackLabel.setText("Save Unsuccessful");
    }
    
    public void refresh(){
        if (mco.allCovers.size()>0)
        {
            saveButton.setEnabled(true);
        }
        else
        {
            saveButton.setEnabled(false);    
        }
    }
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify                     
    private javax.swing.JLabel feedbackLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton menuAddCoverButton;
    private javax.swing.JButton menuSearchForCoverButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration      
    }//GEN-LAST:event_loadButtonActionPerformed

/*
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        mco.writeJson();
    }//GEN-LAST:event_saveButtonActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel feedbackLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton menuAddCoverButton;
    private javax.swing.JButton menuSearchForCoverButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
*/
